project/account/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from django.conf import settings
from django.views.generic import TemplateView
from . import views as auth_views

app_name='account'
urlpatterns = [
	#注意基本类的视图的写法 .as_view(template_name= TemplateName),不再是{"template_name":"account/logout.html"},后者是基于视图的写法
	#django2.1已经使用基于类的视图代替了基于函数的视图,不过真用基于视图的也可以

    ##基于类的视图

    ##登录与注册
	path('login/', auth_views.LoginView.as_view(template_name='account/login.html'), name="user_login"),
	path('logout/', auth_views.LogoutView.as_view(template_name='account/login.html'), name="user_logout"),
	path('register/', auth_views.RegistrationView.as_view(), name="user_register"),

    ##基本信息修改
	re_path(r'^user-profile/(?P<tab>[1,2])/$', auth_views.UserProfileView.as_view(), name="user_profile"),
	path('save-userinfo/', auth_views.UserProfileView.as_view(), name="save_userinfo"),
	path('my-headimage/', auth_views.MineHeadImage.as_view(), name="my_headimage"),

    ##密码修改
	path('password-change/', auth_views.PasswordChangeView.as_view(template_name='account/user_profile.html',success_url='/account/password-change-done/'), name="password_change"),
	path('password-change-done/', auth_views.PasswordChangeDoneView.as_view(template_name='account/user_profile.html'), name="password_change_done"),

    ##密码重置
	path('password-reset/', auth_views.PasswordResetView.as_view(
                                template_name='account/password_reset_form.html',
                                email_template_name='account/password_reset_email.html',
                                subject_template_name='account/password_reset_subject.txt',
                                success_url='/account/password-reset-done/'), name="password_reset"),
	path('password-reset-done/', auth_views.PasswordResetDoneView.as_view(
                                template_name='account/password_reset_done.html'), name="password_reset_done"),
	re_path(r'^password-reset-confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', auth_views.PasswordResetConfirmView.as_view(
                                template_name='account/password_reset_confirm.html',
                                success_url='/account/password-reset-complete/'), name="password_reset_confirm"),
	path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
                                template_name='account/password_reset_complete.html',
                                ), name="password_reset_complete"),


    ##基于函数的视图 django 低版本中可以使用url来指定URL,2.0版本之后弃用了url,改成了path
	#url(r'^login/$', auth_views.login, {"template_name":"account/login.html"}, name="user_login"), #也可以使用,不推荐使用
	#url(r'^logout/$', auth_views.logout,{"template_name":"account/login.html"}, name="user_logout"),
	#url(r'^user-profile/$', TemplateView.as_view(template_name='account/user_profile.html'), name="user_profile"),

    ##密码修改
	##template_name是给get请求使用, post_change_redirect是给post请求使用的
	#url(r'^password-change/$', auth_views.password_change,{"template_name":"account/user_profile.html","post_change_redirect":"/account/password-change-done/"}, name="password_change"),
	#url(r'^password-change-done/$', auth_views.password_change_done,{"template_name":"account/user_profile.html"}, name="password_change_done"),
    
    ##密码重置
	#url(r'^password-reset/$', auth_views.password_reset,{
    #                            "template_name":"account/password_reset_form.html",
    #                            "email_template_name":"account/password_reset_email.html",
    #                            "subject_template_name":"account/password_reset_subject.txt",
    #                            "post_reset_redirect":"/account/password-reset-done/"}, name="password_reset"),
	#url(r'^password-reset-done/$', auth_views.password_reset_done,{
    #                            "template_name":"account/password_reset_done.html"}, name="password_reset_done"),
	#url(r'^password-reset-confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', auth_views.password_reset_confirm,{
    #                            "post_reset_redirect":"/account/password-reset-complete/",
    #                            "template_name":"account/password_reset_confirm.html",}, name="password_reset_confirm"),
	#url(r'^password-reset-complete/$', auth_views.password_reset_complete, {
    #                             "template_name":"account/password_reset_complete.html"}, name="password_reset_complete"),
]

project/customer/urls.py
from django.contrib import admin
from django.urls import path,re_path
from django.conf.urls import url,include
from django.views.generic import TemplateView
from . import views as customer_views

from django.conf import settings

app_name='customer'
urlpatterns = [
    path('list', customer_views.CustomerListPageView.as_view(), name='show_customerList'),
    path('add', customer_views.CustomerAddPageView.as_view(), name='show_customerAdd'),
    path('<int:pk>/delete', customer_views.CustomerDelPageView.as_view(), name='show_customerDel'),
    path('<int:pk>/detail', customer_views.CustomerDetailPageView.as_view(), name='show_customerDetail'),
    path('<int:pk>/update', customer_views.CustomerUpdatePageView.as_view(), name='show_customerUpdate'),

    ##修改记录时有两种方式
    ##一是先用DetailView类获取要修改的对象将对象的数据回显到修改表单中,再使用UpdateView类去更新对象
    ##二是直接使用UpdateView类对象,在XXX_UpdateView类中添加一个获取对象的函数即可(get_context_data)
]

project/main/urls.py
from django.contrib import admin
from django.urls import path,re_path
from django.conf.urls import url,include
from django.views.generic import TemplateView

from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

from account import views as auth_views
from common import views as comm_views

urlpatterns = [
    #登录页
    #直接访问IP:port 后边不用加路径, 即http://192.168.5.105:8000就会跳转到login.html
    #方法一,这样不会在html模板中使用{{form.password}}
	#url('', TemplateView.as_view(template_name="account/login.html"), name='show_loginPage'),
    #方法二,这样可以在html模板中使用{{form.password}}
	path('', auth_views.LoginView.as_view(template_name='account/login.html'), name="show_loginPage"),

    #登录之后跳转到该页,该页即首页
    path('index/', comm_views.IndexPageView.as_view(), name='show_index'),
    path('homepage/', comm_views.HomePageView.as_view(), name='show_homePage'),

    #账户相关
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),

    #客户相关
    path('index/customer/', include('customer.urls', namespace='customer')),

    #订单相关
    path('index/order/', include('order.urls', namespace='order')),

    re_path(r'media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/order/urls.py
from django.contrib import admin
from django.urls import path,re_path
from django.conf.urls import url,include
from django.views.generic import TemplateView
from . import views as order_views

from django.conf import settings

app_name='order'
urlpatterns = [
    path('list', order_views.OrderListPageView.as_view(), name='show_orderList'),
    path('add', order_views.OrderAddPageView.as_view(), name='show_orderAdd'),
    path('<int:pk>/delete', order_views.OrderDelPageView.as_view(), name='show_orderDel'),
    path('<int:pk>/update', order_views.OrderUpdatePageView.as_view(), name='show_orderUpdate'),
    path('casex/<int:cid>', order_views.OrderListCaseExpireView.as_view(), name='show_orderListCase'),
    ##re_path('casex/(?P<cid>\w+)$', order_views.OrderListCaseExpireView.as_view(), name='show_orderListCase'), ##和上边一行功能一样,两种实现方式
    ##path('<int:pk>/detail', order_views.OrderDetailPageView.as_view(), name='show_orderDetail'),
]

project/templates/frame/content.html
{% load staticfiles %}
<!-- 右侧主体开始 -->
<div class="page-content">
    <div class="layui-tab tab" lay-filter="xbs_tab" lay-allowclose="false">
        <ul class="layui-tab-title">
            <li class="home">
                <i class="layui-icon">&#xe68e;</i>我的桌面
            </li>
        </ul>
        <div class="layui-unselect layui-form-select layui-form-selected" id="tab_right">
            <dl>
                <dd data-type="this">关闭当前</dd>
                <dd data-type="other">关闭其它</dd>
                <dd data-type="all">关闭全部</dd></dl>
        </div>
        <div class="layui-tab-content">
            <div class="layui-tab-item layui-show">
                <iframe src="{% url 'show_homePage' %}" frameborder="0" scrolling="yes" class="x-iframe"></iframe>
            </div>
        </div>
        <div id="tab_show"></div>
    </div>
</div>
<div class="page-content-bg"></div>
<style id="theme_style"></style>
<!-- 右侧主体结束 -->

project/templates/frame/header.html
{% load staticfiles %}
<!-- 顶部开始 -->
<div class="container">
    <div class="logo">
        <a href="{% url 'show_index' %}">X-admin v2.2</a></div>
    <div class="left_open">
        <a><i title="展开左侧栏" class="iconfont">&#xe699;</i></a>
    </div>
    <ul class="layui-nav left fast-add" lay-filter="">
        <li class="layui-nav-item">
            <a href="javascript:;">+新增</a>
            <dl class="layui-nav-child">
                <!-- 二级菜单 -->
                <dd>
                    <a onclick="xadmin.open('最大化','http://www.baidu.com','','',true)">
                        <i class="iconfont">&#xe6a2;</i>弹出最大化</a></dd>
                <dd>
                    <a onclick="xadmin.open('弹出自动宽高','http://www.baidu.com')">
                        <i class="iconfont">&#xe6a8;</i>弹出自动宽高</a></dd>
                <dd>
                    <a onclick="xadmin.open('弹出指定宽高','http://www.baidu.com',500,300)">
                        <i class="iconfont">&#xe6a8;</i>弹出指定宽高</a></dd>
                <dd>
                    <a onclick="xadmin.add_tab('在tab打开','member-list.html')">
                        <i class="iconfont">&#xe6b8;</i>在tab打开</a></dd>
                <dd>
                    <a onclick="xadmin.add_tab('在tab打开刷新','member-del.html',true)">
                        <i class="iconfont">&#xe6b8;</i>在tab打开刷新</a></dd>
            </dl>
        </li>
    </ul>
    <ul class="layui-nav right" lay-filter="">
        <li class="layui-nav-item">
            <a href="javascript:;">
                {% if user.is_authenticated%}
                    {{ user.username}}
                {% endif %}
            </a>
            <dl class="layui-nav-child">
                <!-- 二级菜单 -->
                <dd>
                    <a onclick="xadmin.open('个人信息','http://www.baidu.com')">个人信息</a></dd>
                <dd>
                    <a onclick="xadmin.open('切换帐号','http://www.baidu.com')">切换帐号</a></dd>
                <dd>
                    <a href="{% url 'account:user_logout' %}">退出</a></dd>
            </dl>
        </li>
        <li class="layui-nav-item to-index">
            <a href="/">前台首页</a></li>
    </ul>
</div>
<!-- 顶部结束 -->

project/templates/frame/homepage.html
{% load staticfiles %}
<!DOCTYPE html>
<html class="x-admin-sm">
    <head>
        <meta charset="UTF-8">
        <title>欢迎页面-X-admin2.2</title>
        <meta name="renderer" content="webkit">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi" />
        <link rel="stylesheet" href="{% static 'X-admin/css/font.css' %}">
        <link rel="stylesheet" href="{% static 'X-admin/css/xadmin.css' %}">
        <script src="{% static 'X-admin/lib/layui/layui.js' %}" charset="utf-8"></script>
        <script type="text/javascript" src="{% static 'X-admin/js/xadmin.js' %}"></script>
        <!-- 让IE8/9支持媒体查询，从而兼容栅格 -->
        <!--[if lt IE 9]>
            <script type="text/javascript" src="{% static 'common/js/html5.min.js' %}"></script>
            <script type="text/javascript" src="{% static 'common/js/respond.min.js' %}"></script>
        <![endif]-->
    </head>
    <body>
        <div class="layui-fluid">
            <div class="layui-row layui-col-space15">
                <div class="layui-col-md12">
                    <div class="layui-card">
                        <div class="layui-card-body ">
                            <blockquote class="layui-elem-quote">欢迎管理员：
                                <span class="x-red">{% if user.is_authenticated%}{{ user.username}}{% endif %}</span>！当前时间: {% now "Y-m-d H:i:s" %}
                            </blockquote>
                        </div>
                    </div>
                </div>
                <div class="layui-col-md12">
                    <div class="layui-card">
                        <div class="layui-card-header">数据统计</div>
                        <div class="layui-card-body ">
                            <ul class="layui-row layui-col-space10 layui-this x-admin-carousel x-admin-backlog">
                                <li class="layui-col-md2 layui-col-xs6">
                                    <a onclick="xadmin.open('客户列表', '{% url 'customer:show_customerList' %}')" class="x-admin-backlog-body">
                                        <h3>客户总数</h3>
                                        <p>
                                            <cite>{{customerNum}}</cite></p>
                                    </a>
                                </li>
                                <li class="layui-col-md2 layui-col-xs6">
                                    <a  onclick="xadmin.open('订单列表', '{% url 'order:show_orderList' %}')" class="x-admin-backlog-body">
                                        <h3>订单总数</h3>
                                        <p>
                                            <cite>{{orderNum}}</cite></p>
                                    </a>
                                </li>
                                <li class="layui-col-md2 layui-col-xs6">
                                    <a  onclick="xadmin.open('逾期订单', '{% url 'order:show_orderListCase' 1 %}')" class="x-admin-backlog-body">
                                        <h3>逾期订单</h3>
                                        <p>
                                            <cite style="color:red">{{expired}}</cite></p>
                                    </a>
                                </li>
                                <li class="layui-col-md2 layui-col-xs6">
                                    <a  onclick="xadmin.open('今天到期订单', '{% url 'order:show_orderListCase' 2 %}')" class="x-admin-backlog-body">
                                        <h3>今天到期</h3>
                                        <p>
                                            <cite>{{normal}}</cite></p>
                                    </a>
                                </li>
                                <li class="layui-col-md2 layui-col-xs6">
                                    <a  onclick="xadmin.open('3天内要逾期订单', '{% url 'order:show_orderListCase' 3 %}')" class="x-admin-backlog-body">
                                        <h3>3天内要逾期</h3>
                                        <p>
                                            <cite style="color:orange">{{day3expired}}</cite></p>
                                    </a>
                                </li>
                                <li class="layui-col-md2 layui-col-xs6 ">
                                    <a  onclick="xadmin.open('7天内要逾期订单', '{% url 'order:show_orderListCase' 4 %}')" class="x-admin-backlog-body">
                                        <h3>7天内要逾期</h3>
                                        <p>
                                            <cite>{{day7expired}}</cite></p>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="layui-col-sm6 layui-col-md3">
                    <div class="layui-card">
                        <div class="layui-card-header">下载
                            <span class="layui-badge layui-bg-cyan layuiadmin-badge">月</span></div>
                        <div class="layui-card-body  ">
                            <p class="layuiadmin-big-font">33,555</p>
                            <p>新下载
                                <span class="layuiadmin-span-color">10%
                                    <i class="layui-inline layui-icon layui-icon-face-smile-b"></i></span>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="layui-col-sm6 layui-col-md3">
                    <div class="layui-card">
                        <div class="layui-card-header">下载
                            <span class="layui-badge layui-bg-cyan layuiadmin-badge">月</span></div>
                        <div class="layui-card-body ">
                            <p class="layuiadmin-big-font">33,555</p>
                            <p>新下载
                                <span class="layuiadmin-span-color">10%
                                    <i class="layui-inline layui-icon layui-icon-face-smile-b"></i></span>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="layui-col-sm6 layui-col-md3">
                    <div class="layui-card">
                        <div class="layui-card-header">下载
                            <span class="layui-badge layui-bg-cyan layuiadmin-badge">月</span></div>
                        <div class="layui-card-body ">
                            <p class="layuiadmin-big-font">33,555</p>
                            <p>新下载
                                <span class="layuiadmin-span-color">10%
                                    <i class="layui-inline layui-icon layui-icon-face-smile-b"></i></span>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="layui-col-sm6 layui-col-md3">
                    <div class="layui-card">
                        <div class="layui-card-header">下载
                            <span class="layui-badge layui-bg-cyan layuiadmin-badge">月</span></div>
                        <div class="layui-card-body ">
                            <p class="layuiadmin-big-font">33,555</p>
                            <p>新下载
                                <span class="layuiadmin-span-color">10%
                                    <i class="layui-inline layui-icon layui-icon-face-smile-b"></i></span>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="layui-col-md12">
                    <div class="layui-card">
                        <div class="layui-card-header">系统信息</div>
                        <div class="layui-card-body ">
                            <table class="layui-table">
                                <tbody>
                                    <tr>
                                        <th>xxx版本</th>
                                        <td>1.0.180420</td></tr>
                                    <tr>
                                        <th>服务器地址</th>
                                        <td>x.xuebingsi.com</td></tr>
                                    <tr>
                                        <th>操作系统</th>
                                        <td>WINNT</td></tr>
                                    <tr>
                                        <th>运行环境</th>
                                        <td>Apache/2.4.23 (Win32) OpenSSL/1.0.2j mod_fcgid/2.3.9</td></tr>
                                    <tr>
                                        <th>PHP版本</th>
                                        <td>5.6.27</td></tr>
                                    <tr>
                                        <th>PHP运行方式</th>
                                        <td>cgi-fcgi</td></tr>
                                    <tr>
                                        <th>MYSQL版本</th>
                                        <td>5.5.53</td></tr>
                                    <tr>
                                        <th>ThinkPHP</th>
                                        <td>5.0.18</td></tr>
                                    <tr>
                                        <th>上传附件限制</th>
                                        <td>2M</td></tr>
                                    <tr>
                                        <th>执行时间限制</th>
                                        <td>30s</td></tr>
                                    <tr>
                                        <th>剩余空间</th>
                                        <td>86015.2M</td></tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="layui-col-md12">
                    <div class="layui-card">
                        <div class="layui-card-header">开发团队</div>
                        <div class="layui-card-body ">
                            <table class="layui-table">
                                <tbody>
                                    <tr>
                                        <th>版权所有</th>
                                        <td>xuebingsi(xuebingsi)
                                            <a href="http://x.xuebingsi.com/" target="_blank">访问官网</a></td>
                                    </tr>
                                    <tr>
                                        <th>开发者</th>
                                        <td>马志斌(113664000@qq.com)</td></tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <style id="welcome_style"></style>
            </div>
        </div>
        </div>
    </body>
</html>

project/templates/frame/index.html
{% load staticfiles %}
<!doctype html>
<html class="x-admin-sm">
    <head>
        <meta charset="UTF-8">
        <title>后台登录-X-admin2.2</title>
        <meta name="renderer" content="webkit|ie-comp|ie-stand">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi" />
        <meta http-equiv="Cache-Control" content="no-siteapp" />
        <link rel="stylesheet" href="{% static 'X-admin/css/font.css' %}">
        <link rel="stylesheet" href="{% static 'X-admin/css/xadmin.css' %}">
        <!-- <link rel="stylesheet" href="./css/theme5.css"> -->
        <script src="{% static 'X-admin/lib/layui/layui.js' %}" charset="utf-8"></script>
        <script type="text/javascript" src="{% static 'X-admin/js/xadmin.js' %}"></script>
        <!-- 让IE8/9支持媒体查询，从而兼容栅格 -->
        <!--[if lt IE 9]>
        <script type="text/javascript" src="{% static 'common/js/html5.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'common/js/respond.min.js' %}"></script>
        <![endif]-->
        <script>
            // 是否开启刷新记忆tab功能
             var is_remember = true;
        </script>
    </head>
    <body class="index">
        {% include "frame/header.html" %}
        {% include "frame/sidebar.html" %}
        {% include "frame/content.html" %}
    </body>
</html>

project/templates/frame/searchBindMode.html
<script type="text/javascript">
    document.onkeydown = function(e){
        var e = event.srcElement;
        if (event.keyCode == 13)
        {
            document.getElementById("searchBtn").click();
            return false;
        }
    }
</script>

project/templates/frame/tabpages.html
{% load staticfiles %}
<!DOCTYPE html>
<html class="x-admin-sm">
    <head>
        <meta charset="UTF-8">
        <title>欢迎页面-X-admin2.2</title>
        <meta name="renderer" content="webkit">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi" />
        <link rel="stylesheet" href="{% static 'X-admin/css/font.css' %}">
        <link rel="stylesheet" href="{% static 'X-admin/css/xadmin.css' %}">
        <script type="text/javascript" src="{% static 'X-admin/js/jquery.min.js' %}"></script>
        <script src="{% static 'X-admin/lib/layui/layui.js' %}" charset="utf-8"></script>
        <script type="text/javascript" src="{% static 'X-admin/js/xadmin.js' %}"></script>
        <script type="text/javascript" src="{% static 'common/js/csrf.js' %}"></script>
        <!-- 让IE8/9支持媒体查询，从而兼容栅格 -->
        <!--[if lt IE 9]>
            <script type="text/javascript" src="{% static 'common/js/html5.min.js' %}"></script>
            <script type="text/javascript" src="{% static 'common/js/respond.min.js' %}"></script>
        <![endif]-->
    </head>
    {% block content %}{% endblock %}
    {% block jsscript%}{% endblock %}
</html>