project/main/urls.py
from django.contrib import admin
from django.urls import path,re_path
from django.conf.urls import url,include
from django.views.generic import TemplateView

from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

from account import views as auth_views
from common import views as comm_views

urlpatterns = [
    #登录页
    #直接访问IP:port 后边不用加路径, 即http://192.168.5.105:8000就会跳转到login.html
    #方法一,这样不会在html模板中使用{{form.password}}
	#url('', TemplateView.as_view(template_name="account/login.html"), name='show_loginPage'),
    #方法二,这样可以在html模板中使用{{form.password}}
	path('', auth_views.LoginView.as_view(template_name='account/login.html'), name="show_loginPage"),

    #登录之后跳转到该页,该页即首页
    path('index/', comm_views.IndexPageView.as_view(), name='show_index'),
    path('homepage/', comm_views.HomePageView.as_view(), name='show_homePage'),

    #账户相关
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),

    #客户相关
    path('index/customer/', include('customer.urls', namespace='customer')),

    #订单相关
    path('index/order/', include('order.urls', namespace='order')),

    re_path(r'media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/order/urls.py
from django.contrib import admin
from django.urls import path,re_path
from django.conf.urls import url,include
from django.views.generic import TemplateView
from . import views as order_views

from django.conf import settings

app_name='order'
urlpatterns = [
    path('list', order_views.OrderListPageView.as_view(), name='show_orderList'),
    path('add', order_views.OrderAddPageView.as_view(), name='show_orderAdd'),
    path('<int:pk>/delete', order_views.OrderDelPageView.as_view(), name='show_orderDel'),
    path('<int:pk>/update', order_views.OrderUpdatePageView.as_view(), name='show_orderUpdate'),
    path('casex/<int:cid>', order_views.OrderListCaseExpireView.as_view(), name='show_orderListCase'),
    ##re_path('casex/(?P<cid>\w+)$', order_views.OrderListCaseExpireView.as_view(), name='show_orderListCase'), ##和上边一行功能一样,两种实现方式
    ##path('<int:pk>/detail', order_views.OrderDetailPageView.as_view(), name='show_orderDetail'),
]

project/order/models.py
from django.db import models
from django import forms
from django.conf import settings
from customer.models import CustomerModel

import datetime

# Create your models here.

class OrderModel(models.Model):
    orderid = models.CharField(max_length=24, blank=False, null=False)
    customer = models.ForeignKey(CustomerModel, on_delete=models.CASCADE, blank=False, null=False, related_name='rn_Order_Customer')
    contact = models.CharField(max_length=24, blank=False, null=False)
    phone = models.CharField(max_length=11, default=False, null=False)

    deposit = models.DecimalField(max_digits=10, decimal_places=2, blank=False, null=False)
    price = models.DecimalField(max_digits=10, decimal_places=2, blank=False, null=False)
    effectdays = models.PositiveSmallIntegerField(blank=True, null=False)
    balance = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=False)
    comment = models.CharField(max_length=100, blank=True, null=True)
    orderdate = models.DateTimeField(blank=False, null=False)

    class Meta:
        ordering = ('-id',)
    
    def __str__(self):
        return 'order:{},{},{},{},{},{},{}'.format(self.orderid, self.customer, self.contact,self.deposit, self.price, self.effectdays, self.balance)
    
    def get_effect_days(self):
        date_format = "%m/%d/%Y"
        now = datetime.datetime.now()
        print ("=============================date", self.orderdate)
        print ("=============================comment", self.comment)
        delta = now - self.orderdate
        return delta.days + 1

    def get_balance(self):
        balance = self.deposit - self.price * self.get_effect_days() 
        return balance

    def get_after7days_expire(self):
        if self.balance < self.price * 7 :
            return 1 
        else:
            return 0

    def get_after7days_expire(self):
        if self.balance < self.price * 3 :
            return 1 
        else:
            return 0

    def get_expired(self):
        if self.balance < 0 :
            return 1 
        else:
            return 0

project/order/forms.py
from django import forms
from .models import OrderModel 

class OrderAddForm(forms.ModelForm):
    class Meta:
        model = OrderModel 
        fields = ("orderid","customer","contact","phone","deposit",
                  "price", "comment", "orderdate")

project/order/views.py
from django.shortcuts import render, redirect
from braces.views import LoginRequiredMixin
from django.views.generic import CreateView, ListView, DeleteView, UpdateView, DetailView
from django.views.generic.base import TemplateView
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.http import HttpResponse, JsonResponse
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import F ##一个数据库中的两个字段比较需要用到
import json

from customer.models import CustomerModel as Customer
from .models import OrderModel as Order
from .forms import OrderAddForm 

# Create your views here.

##BEGIN: Add by SRJ-SGL 
#客户列表
class OrderListCaseExpireView(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('user_login') 
    template_name = "order/order-list-case.html"

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {"cid": kwargs.get('cid')})

    def post(self, request, *args, **kwargs):
        ## 过滤条件参数
        ## 判断是搜索的数据还是直接显示的数据
        q = {}
        q['balance__gte'] = 0
        page = request.POST.get('page')
        rows = request.POST.get('limit')
        cid = kwargs.get('cid')

        if cid == 1:  ##已逾期
            q = {}
            q['balance__lt'] = 0
        elif cid == 2:  ##今天到期
            q['balance__lte'] = F('price')
        elif cid == 3:   ##3天内将要逾期
            q['balance__lte'] = F('price') * 3
        elif cid == 4:  ##7天内将要逾期
            q['balance__lte'] = F('price') * 7

        orders = Order.objects.filter(**q)
        total = orders.count()

        start = (int(page) - 1) * int(rows)
        end = (int(page) - 1) * int(rows) + int(rows)

        total = orders.count()
        orders = orders[start:end]

        dict = []
        resultdict = {}

        for tmp in orders:
            dic = {}
            dic['id'] = tmp.id
            dic['orderid'] = tmp.orderid
            dic['customer'] = tmp.customer.name
            dic['contact'] = tmp.contact
            dic['phone'] = tmp.phone
            dic['deposit'] = tmp.deposit
            dic['price'] = tmp.price
            dic['effectdays'] = tmp.effectdays
            dic['balance'] = tmp.balance
            dic['comment'] = tmp.comment
            dic['orderdate'] = tmp.orderdate.strftime("%Y-%m-%d")
            dict.append(dic)

        resultdict['code'] = 0
        resultdict['msg'] = ""
        resultdict['count'] = total 
        resultdict['data'] = dict

        return JsonResponse(resultdict, safe=False) 

class OrderListPageView(LoginRequiredMixin, ListView):
    ## login_url = "/account/login/"  和下边一行的功能是一样的,一个是硬编码,一个是灵活实现
    login_url = reverse_lazy('user_login') 
    template_name = "order/order-list.html"
    search_fields = ('orderid', 'customer__name', 'contact', 'phone', 'orderdate')

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request, *args, **kwargs):
        ## 过滤条件参数
        ## 判断是搜索的数据还是直接显示的数据
        q = {}
        page = request.POST.get('page')
        rows = request.POST.get('limit')

        filter_orderid = request.POST.get('filter_orderid')         
        filter_customer = request.POST.get('filter_customer')         
        filter_contact = request.POST.get('filter_contact')         
        filter_phone = request.POST.get('filter_phone')         
        filter_orderdate = request.POST.get('filter_orderdate')
        
        if filter_orderid:
            q['orderid__icontains'] = filter_orderid
        if filter_customer: ##外键不能直接过滤,需要指定过滤外键的哪个字段
            q['customer__name__icontains'] = filter_customer
        if filter_contact:
            q['contact__icontains'] = filter_contact
        if filter_phone:
            q['phone__icontains'] = filter_phone
        if filter_orderdate:
            q['orderdate__icontains'] = filter_orderdate

        orders = Order.objects.filter(**q)

        start = (int(page) - 1) * int(rows)
        end = (int(page) - 1) * int(rows) + int(rows)

        total = orders.count()
        orders = orders[start:end]

        dict = []
        resultdict = {}

        for tmp in orders:
            dic = {}
            dic['id'] = tmp.id
            dic['orderid'] = tmp.orderid
            dic['customer'] = tmp.customer.name
            dic['contact'] = tmp.contact
            dic['phone'] = tmp.phone
            dic['deposit'] = tmp.deposit
            dic['price'] = tmp.price
            dic['effectdays'] = tmp.effectdays
            dic['balance'] = tmp.balance
            dic['comment'] = tmp.comment
            dic['orderdate'] = tmp.orderdate.strftime("%Y-%m-%d")
            dict.append(dic)

        resultdict['code'] = 0
        resultdict['msg'] = ""
        resultdict['count'] = total 
        resultdict['data'] = dict

        return JsonResponse(resultdict, safe=False) 

class OrderAddPageView(LoginRequiredMixin, CreateView):
    login_url = "/account/login/"
    template_name = "order/order-add.html"
    ## fileds为页面上的表单要显示的项
    ##fields = ['orderid', 'customer', 'contact', 'phone', 'deposit',
    ##          'price', 'comment']

    ##Note1 此处只能使用这个,因为要返回customers做为下拉列表的内容 
    def get(self, request):
        customers = Customer.objects.all()
        return render(request, "order/order-add.html", {"customers":customers})
    
    ##Note2 当继承的是CreateView时使用这个,功能与Note1是一样的,只是两种不同的实现方式
    ##queryset = Order.objects.all()

    def post(self, request, *args, **kwargs):
        formObj = OrderAddForm(request.POST)
        resultdict = {}

        if formObj.is_valid():
            form_cd = formObj.cleaned_data 

            new_order = formObj.save(commit=False) ## form.save(commit=False)返回的是一个Model对象

            new_order.effectdays = new_order.get_effect_days()
            new_order.balance = new_order.get_balance()
            new_order.save(form_cd)

            resultdict['code'] = 0
            resultdict['msg'] = ""
            return JsonResponse(resultdict, safe=False) 
        else:
            print ("===================xxxx",formObj.errors)

        return self.render_to_response({"form":formObj})

class OrderDelPageView(LoginRequiredMixin, DeleteView):
    login_url = "/account/login/"
    success_url = reverse_lazy('order:show_orderList')

    model = Order

    def delete(self, request, *args, **kwargs):
        ##for k, v in kwargs.items():
        ##    print ('%s，%s；' , (k, v))
        super(OrderDelPageView, self).delete(request, *args, **kwargs)
        return JsonResponse({'code':0, 'msg':''}) 

##class OrderDetailPageView(LoginRequiredMixin, DeleteView):
##    template_name = "order/order-update.html"
##    context_object_name = "order"
##
##    model = Order
##
##    ##如果不要下边的这个函数,是不会把信息返回到表单的
##    ##def get_object(self, queryset=None):
##    ##    obj = super(OrderDetailPageView, self).get_object()
##    ##    return obj
##
##    ##下边注释的两个函数其实放开效果是一样的,只不过是记录一下怎么取url中的参数的方法
##    ##def get_object(self,queryset=None):
##    ##    obj_id = int(self.kwargs.get(self.pk_url_kwarg, None))
##    ##    obj = self.model.objects.get(id = obj_id)
##    ##    return obj 
##    
##    def get_context_data(self, **kwargs):
##        context = super(OrderDetailPageView, self).get_context_data(**kwargs)
##        return context
##
class OrderUpdatePageView(LoginRequiredMixin, UpdateView):
    login_url = "/account/login/"
    success_url = reverse_lazy('order:show_orderList')

    template_name = "order/order-update.html"
    template_name_suffix = '_update_form'
    fields = ['contact', 'phone', 'deposit', 'price', 'comment']
    context_object_name = "order"

    model = Order

    ##def get_form_kwargs(self):
    ##    kwargs = super(OrderUpdatePageView,self).get_form_kwargs()
    ##    print ("==============kwargs id", self.kwargs['pk'])
    ##    return kwargs

    def post(self, request, *args, **kwargs):
        formObj = OrderAddForm(request.POST)
        resultdict = {}

        if formObj.is_valid():
            form_cd = formObj.cleaned_data 

            order = Order.objects.get(id=self.kwargs['pk']) 
            order.contact = form_cd['contact']  
            order.phone = form_cd['phone']  
            order.deposit = form_cd['deposit']  
            order.price = form_cd['price']
            order.orderdate = form_cd['orderdate']
            order.comment = form_cd['comment']

            order.effectdays = order.get_effect_days()
            order.balance = order.get_balance()

            order.save()

            resultdict['code'] = 0
            resultdict['msg'] = ""
            return JsonResponse(resultdict, safe=False) 
        else:
            print ("===================xxxx",formObj.errors)

        return self.render_to_response({"form":formObj})
####END: Add by SRJ-SGL 

project/templates/order/order-add.html
{% extends "frame/tabpages.html" %}
{% block content %}
<body>
    <div class="layui-fluid">
        <div class="layui-row">
            <form class="layui-form" id="id_addOrderForm">
                <div class="layui-form-item">
                    <label for="id_orderid" class="layui-form-label">
                        <span class="x-red">*</span>订单编号</label>
                    <div class="layui-input-inline">
                        <input type="text" id="id_orderid" name="orderid" required="" lay-verify="required" autocomplete="off" class="layui-input" value="hello"></div>
                </div>
                <div class="layui-form-item">
                    <label for="id_customer" class="layui-form-label">
                        <span class="x-red">*</span>客户名称</label>
                    <div class="layui-input-inline">
                        <select name="customer">
                            <option value="">请选择<option>
                            {% for customer in customers %}
                            <option value="{{customer.id}}">{{customer.name}}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="layui-form-item">
                    <label for="id_contact" class="layui-form-label">
                        <span class="x-red">*</span>收货人</label>
                    <div class="layui-input-inline">
                        <input type="text" id="id_contact" name="contact" required="" lay-verify="required" autocomplete="off" class="layui-input" value="song"></div>
                </div>
                <div class="layui-form-item">
                    <label for="id_phone" class="layui-form-label">
                        <span class="x-red">*</span>手机</label>
                    <div class="layui-input-inline">
                        <input type="text" id="id_phone" name="phone" required="" lay-verify="phone" autocomplete="off" class="layui-input" value="18600335242"></div>
                </div>
                <div class="layui-form-item">
                    <label for="id_deposit" class="layui-form-label">
                        <span class="x-red">*</span>压金</label>
                    <div class="layui-input-inline">
                        <input type="text" id="id_deposit" name="deposit" placeholder="单位:元" required="" lay-verify="number" autocomplete="off" class="layui-input" value="1000.00"></div>
                </div>
                <div class="layui-form-item">
                    <label for="id_price" class="layui-form-label">
                        <span class="x-red">*</span>费用/日</label>
                    <div class="layui-input-inline">
                        <input type="text" id="id_price" name="price" required="" lay-verify="number" autocomplete="off" class="layui-input" value="100.00"></div>
                </div>
                <div class="layui-form-item">
                    <label for="id_orderdate" class="layui-form-label">
                        <span class="x-red">*</span>下单日期</label>
                    <div class="layui-input-inline">
                        <input class="layui-input" id="id_orderdate" name="orderdate" lay-verify="date"></div>
                </div>
                <div class="layui-form-item layui-form-text">
                    <label for="id_comment" class="layui-form-label">描述</label>
                    <div class="layui-input-block">
                        <textarea placeholder="请输入内容" id="id_comment" name="comment" class="layui-textarea"></textarea>
                    </div>
                </div>
                <div class="layui-form-item">
                    <label class="layui-form-label"></label>
                    <button class="layui-btn" lay-filter="add" lay-submit="">增加</button>
                    <button class="layui-btn" lay-filter="continue" lay-submit="">增加后继续</button>
                </div>
    </form>
    </div>
    </div>
</body>
{% endblock %}

{% block jsscript %}
<script>
    layui.use(['laydate', 'form', 'layer'],
    function() {
        $ = layui.jquery;
        var form = layui.form,
        laydate = layui.laydate,
        layer = layui.layer;
        
        laydate.render({
            elem: '#id_orderdate'
        });
        
        //监听提交
        form.on('submit(add)',
        function(data) {
            $.ajax({
                type:'post',
                url:"{% url 'order:show_orderAdd' %}",
                data:data.field,
                success:function(res){
                    if (res.code == 0)
                    {
                       // layer.alert("添加成功", {icon: 6},function() {
                            xadmin.close();//关闭当前frame
                            xadmin.father_reload();// 可以对父窗口进行刷新 
                        //});
                        layer.msg("添加失败.");
                    }
                },
                error:function(res)
                {
                    layer.msg("添加失败.");
                }
            });
                       
            return false;
        });

        form.on('submit(continue)',
        function(data) {
            $.ajax({
                type:'post',
                url:"{% url 'order:show_orderAdd' %}",
                data:data.field,
                success:function(res){
                    if (res.code == 0)
                    {
                        layer.msg("添加成功,继续添加下一个.");
                        $("#id_addOrderForm")[0].reset();
                    }
                },
                error:function(res)
                {
                    layer.msg("添加失败.");
                }
            });
                       
            return false;
        });
    });
</script>
{% endblock %}

project/templates/order/order-list-case.html
{% extends "frame/tabpages.html" %}
{% block content %}
<body>
    <div class="layui-fluid">
        <div class="layui-row layui-col-space15">
            <div class="layui-col-md12">
                <div class="layui-card">
                    <div class="layui-card-body ">
                        <table id="id_orderlist" class="layui-table layui-form" lay-filter="f_orderlist"></table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% include "frame/searchBindMode.html" %}
</body>
{% endblock %}

{% block jsscript %}
<script type="text/html" id="toolbarOper">
    <a class="layui-btn layui-btn-xs" lay-event="edit">编辑</a>
    <a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="del">删除</a>
</script>

<script>
layui.use(['jquery','table', 'laydate'], function(){
    var table = layui.table;
    var laydate = layui.laydate;
    var $ = layui.$;
    var cid = {{cid}}

    laydate.render({
        elem: '#id_orderdate' //指定元素
    });

    table.render({
        elem: '#id_orderlist', 
        method: 'post',
        url: "{% url 'order:show_orderListCase' cid %}", //数据接口
        height: 'full-180',
        cellMinWidth: 50,
        page: true, //开启分页
        limit: 10,
        defaultToolbar: ['filter', 'exports', 'print', { //自定义头部工具栏右侧图标。如无需自定义，去除该参数即可
            title: '提示',
            layEvent: 'LAYTABLE_TIPS',
            icon: 'layui-icon-tips',
            }],
        cols: [[ //表头
            {type: 'numbers',   title: '序号',       width:'5%',  align:'center'},
            {field: 'orderid',  title: '订单编号',   width:'10%', align:'center', sort: true},
            {field: 'customer', title: '客户名称',   width:'10%', align:'center', sort: true},
            {field: 'contact',  title: '联系人',     width:'10%', align:'center', sort: true},
            {field: 'phone',    title: '联系方式',   width:'10%', align:'center', sort: true},
            {field: 'deposit',  title: '压金',       width:'8%',  align:'center', sort: true},
            {field: 'price',    title: '价格/日',    width:'8%',  align:'center', sort: true,
                templet: function(d){
                    return d.price + ' 元';
                }
            },
            {field: 'effectdays', title: '已租', width:'8%',  align:'center', sort: true, 
                templet: function(d){
                    return d.effectdays + ' 天';
                }
            },
            {field: 'balance',    title: '余额',     width:'8%',  align:'center', sort: true},
            {field: 'orderdate',  title: '下单时间', width:'8%',  align:'center', sort: true},
            {field: 'comment',    title: '备注',                  align:'center', sort: true}
        ]]
    });  

    table.on('tool(f_orderlist)', function(obj){
        var data = obj.data;
        if(obj.event === 'del'){
            layer.confirm('确定要删除?', function(index){
                $.ajax({
                    type:'post',
                    url:"{% url 'order:show_orderDel' 0 %}".replace('0', data.id),
                    data:{},
                    success:function(res){
                        if (res.code == 0)
                        {
                            layer.msg("删除成功!");
                            obj.del();
                            layer.close(index);
                        }

                    },
                    error:function(res)
                    {
                        layer.msg("删除失败!");
                    }
                });
            });
        } else if(obj.event === 'edit'){
            uri = obj.data.id + '/update'; 
            xadmin.open('编辑用户',uri,600,400);
        }

    });

    active = {
        delAllChecked: function(){ //获取选中数据
            var checkStatus = table.checkStatus('id_orderlist');
            data = checkStatus.data;
            data.forEach((item, index, array)=>{
                $.ajax({
                    type:'post',
                    url:"{% url 'order:show_orderDel' 0 %}".replace('0', item.id),
                    data:{},
                    success:function(res){
                        if (res.code == 0)
                        {
                            layer.msg("删除成功!");
                            location.reload();
                        }
                    },
                    error:function(res)
                    {
                        layer.msg("删除失败!");
                    }
                });
            })
        },
        reload: function(){
            table.reload('id_orderlist', {
                page: {
                    curr: 1 //重新从第 1 页开始
                },
                where: {
                   filter_orderid: $("input[name=filter_orderid]").val(),
                   filter_customer: $("input[name=filter_customer]").val(),
                   filter_contact: $("input[name=filter_contact]").val(),
                   filter_phone: $("input[name=filter_phone]").val(),
                   filter_orderdate: $("input[name=filter_orderdate]").val()
                }
            });
        },
        reset: function(){
            $("#id_searchOrderForm")[0].reset();
            $("#id_refresh").click();
        }
    };

    $('.xxxListButton .layui-btn').on('click', function(){
        var type = $(this).data('type');
        active[type] ? active[type].call(this) : '';
    });
});
</script>
{% endblock %}

project/templates/order/order-update.html
{% extends "frame/tabpages.html" %}
{% block content %}
<body>
    <div class="layui-fluid">
        <div class="layui-row">
            <form class="layui-form">{% csrf_token %}
                <div class="layui-form-item">
                    <label for="id_orderid" class="layui-form-label">
                        <span class="x-red">*</span>订单编号</label>
                    <div class="layui-input-inline">
                        <input type="text" id="id_orderid" name="orderid" required="" lay-verify="required" autocomplete="off" class="layui-input" value="{{order.orderid}}"></div>
                </div>
                <div class="layui-form-item">
                    <label for="id_customer" class="layui-form-label">
                        <span class="x-red">*</span>客户名称</label>
                    <div class="layui-input-inline">
                        <select name="customer">
                            <option value="{{order.customer.id}}">{{order.customer.name}}<option>
                        </select>
                    </div>
                </div>
                <div class="layui-form-item">
                    <label for="id_contact" class="layui-form-label">
                        <span class="x-red">*</span>收货人</label>
                    <div class="layui-input-inline">
                        <input type="text" id="id_contact" name="contact" lay-verify="required" autocomplete="off" class="layui-input" value="{{order.contact}}"></div>
                </div>
                <div class="layui-form-item">
                    <label for="id_phone" class="layui-form-label">
                        <span class="x-red">*</span>手机</label>
                    <div class="layui-input-inline">
                        <input type="text" id="id_phone" name="phone" lay-verify="phone" autocomplete="on" class="layui-input" value="{{order.phone}}"></div>
                </div>
                <div class="layui-form-item">
                    <label for="id_deposit" class="layui-form-label">
                        <span class="x-red">*</span>压金</label>
                    <div class="layui-input-inline">
                        <input type="text" id="id_deposit" name="deposit" placeholder="单位:元" autocomplete="off" lay-verify="number" class="layui-input" value="{{order.deposit}}"></div>
                </div>
                <div class="layui-form-item">
                    <label for="id_price" class="layui-form-label">
                        <span class="x-red">*</span>费用/日</label>
                    <div class="layui-input-inline">
                        <input type="text" id="id_price" name="price" autocomplete="off" lay-verify="number" class="layui-input" value="{{order.price}}"></div>
                </div>
                <div class="layui-form-item">
                    <label for="id_orderdate" class="layui-form-label">
                        <span class="x-red">*</span>下单日期</label>
                    <div class="layui-input-inline">
                        <input class="layui-input" id="id_orderdate" name="orderdate" lay-verify="date" value="{{order.orderdate}}"></div>
                </div>
                <div class="layui-form-item layui-form-text">
                    <label for="id_comment" class="layui-form-label">描述</label>
                    <div class="layui-input-block">
                        <textarea placeholder="请输入内容" id="id_comment" name="comment" class="layui-textarea">{{order.comment}}</textarea>
                    </div>
                </div>
                <div class="layui-form-item">
                    <label class="layui-form-label"></label>
                    <button class="layui-btn" lay-filter="update" lay-submit="">修改</button>
                </div>
    </form>
    </div>
    </div>
</body>
{% endblock %}

{% block jsscript %}
<script>
layui.use(['laydate', 'form', 'layer'],
function() {
    $ = layui.jquery;
    var form = layui.form,
    laydate = layui.laydate,
    layer = layui.layer;

    laydate.render({
        elem: '#id_orderdate'
    });
    
    //监听提交
    form.on('submit(update)',
    function(data) {
        $.ajax({
            type:'post',
            url:"{% url 'order:show_orderUpdate' 00 %}".replace('0', {{order.id}}),
            data:data.field,
            success:function(res){
                layer.msg("更新成功!");
                xadmin.close();//关闭当前frame
                xadmin.father_reload();// 可以对父窗口进行刷新 
            },
            error:function(res)
            {
                layer.msg("更新失败!");
            }
        });
                   
        return false;
    });
});
</script>
{% endblock %}