project/account/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from django.conf import settings
from django.views.generic import TemplateView
from . import views as auth_views

app_name='account'
urlpatterns = [
	#注意基本类的视图的写法 .as_view(template_name= TemplateName),不再是{"template_name":"account/logout.html"},后者是基于视图的写法
	#django2.1已经使用基于类的视图代替了基于函数的视图,不过真用基于视图的也可以

    ##基于类的视图

    ##登录与注册
	path('login/', auth_views.LoginView.as_view(template_name='account/login.html'), name="user_login"),
	path('logout/', auth_views.LogoutView.as_view(template_name='account/login.html'), name="user_logout"),
	path('register/', auth_views.RegistrationView.as_view(), name="user_register"),

    ##基本信息修改
	re_path(r'^user-profile/(?P<tab>[1,2])/$', auth_views.UserProfileView.as_view(), name="user_profile"),
	path('save-userinfo/', auth_views.UserProfileView.as_view(), name="save_userinfo"),
	path('my-headimage/', auth_views.MineHeadImage.as_view(), name="my_headimage"),

    ##密码修改
	path('password-change/', auth_views.PasswordChangeView.as_view(template_name='account/user_profile.html',success_url='/account/password-change-done/'), name="password_change"),
	path('password-change-done/', auth_views.PasswordChangeDoneView.as_view(template_name='account/user_profile.html'), name="password_change_done"),

    ##密码重置
	path('password-reset/', auth_views.PasswordResetView.as_view(
                                template_name='account/password_reset_form.html',
                                email_template_name='account/password_reset_email.html',
                                subject_template_name='account/password_reset_subject.txt',
                                success_url='/account/password-reset-done/'), name="password_reset"),
	path('password-reset-done/', auth_views.PasswordResetDoneView.as_view(
                                template_name='account/password_reset_done.html'), name="password_reset_done"),
	re_path(r'^password-reset-confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', auth_views.PasswordResetConfirmView.as_view(
                                template_name='account/password_reset_confirm.html',
                                success_url='/account/password-reset-complete/'), name="password_reset_confirm"),
	path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
                                template_name='account/password_reset_complete.html',
                                ), name="password_reset_complete"),


    ##基于函数的视图 django 低版本中可以使用url来指定URL,2.0版本之后弃用了url,改成了path
	#url(r'^login/$', auth_views.login, {"template_name":"account/login.html"}, name="user_login"), #也可以使用,不推荐使用
	#url(r'^logout/$', auth_views.logout,{"template_name":"account/login.html"}, name="user_logout"),
	#url(r'^user-profile/$', TemplateView.as_view(template_name='account/user_profile.html'), name="user_profile"),

    ##密码修改
	##template_name是给get请求使用, post_change_redirect是给post请求使用的
	#url(r'^password-change/$', auth_views.password_change,{"template_name":"account/user_profile.html","post_change_redirect":"/account/password-change-done/"}, name="password_change"),
	#url(r'^password-change-done/$', auth_views.password_change_done,{"template_name":"account/user_profile.html"}, name="password_change_done"),
    
    ##密码重置
	#url(r'^password-reset/$', auth_views.password_reset,{
    #                            "template_name":"account/password_reset_form.html",
    #                            "email_template_name":"account/password_reset_email.html",
    #                            "subject_template_name":"account/password_reset_subject.txt",
    #                            "post_reset_redirect":"/account/password-reset-done/"}, name="password_reset"),
	#url(r'^password-reset-done/$', auth_views.password_reset_done,{
    #                            "template_name":"account/password_reset_done.html"}, name="password_reset_done"),
	#url(r'^password-reset-confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', auth_views.password_reset_confirm,{
    #                            "post_reset_redirect":"/account/password-reset-complete/",
    #                            "template_name":"account/password_reset_confirm.html",}, name="password_reset_confirm"),
	#url(r'^password-reset-complete/$', auth_views.password_reset_complete, {
    #                             "template_name":"account/password_reset_complete.html"}, name="password_reset_complete"),
]

project/main/urls.py
from django.contrib import admin
from django.urls import path,re_path
from django.conf.urls import url,include
from django.views.generic import TemplateView

from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

from account import views as auth_views
from common import views as comm_views

urlpatterns = [
    #登录页
    #直接访问IP:port 后边不用加路径, 即http://192.168.5.105:8000就会跳转到login.html
    #方法一,这样不会在html模板中使用{{form.password}}
	#url('', TemplateView.as_view(template_name="account/login.html"), name='show_loginPage'),
    #方法二,这样可以在html模板中使用{{form.password}}
	path('', auth_views.LoginView.as_view(template_name='account/login.html'), name="show_loginPage"),

    #登录之后跳转到该页,该页即首页
    path('index/', comm_views.IndexPageView.as_view(), name='show_index'),
    path('homepage/', comm_views.HomePageView.as_view(), name='show_homePage'),

    #账户相关
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),

    #客户相关
    path('index/customer/', include('customer.urls', namespace='customer')),

    #订单相关
    path('index/order/', include('order.urls', namespace='order')),

    re_path(r'media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/account/models.py
from django.db import models
from django.contrib.auth.models import User

class UserInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, unique=True, related_name='rn_UserInfo')
    name = models.CharField(max_length=20, blank=True)
    gender = models.BooleanField(default=True)
    birth = models.DateField(blank=True, null=True)
    website = models.URLField(max_length=100, blank=True)
    phone = models.CharField(max_length=15, blank=True)
    comment = models.TextField(max_length=100, blank=True)
    photo = models.ImageField(blank=True)

    def __str__(self):
        return 'user:{},{},{}'.format(self.user.username, self.name, self.phone)

# Create your models here.

project/order/models.py
from django.db import models
from django import forms
from django.conf import settings
from customer.models import CustomerModel

import datetime

# Create your models here.

class OrderModel(models.Model):
    orderid = models.CharField(max_length=24, blank=False, null=False)
    customer = models.ForeignKey(CustomerModel, on_delete=models.CASCADE, blank=False, null=False, related_name='rn_Order_Customer')
    contact = models.CharField(max_length=24, blank=False, null=False)
    phone = models.CharField(max_length=11, default=False, null=False)

    deposit = models.DecimalField(max_digits=10, decimal_places=2, blank=False, null=False)
    price = models.DecimalField(max_digits=10, decimal_places=2, blank=False, null=False)
    effectdays = models.PositiveSmallIntegerField(blank=True, null=False)
    balance = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=False)
    comment = models.CharField(max_length=100, blank=True, null=True)
    orderdate = models.DateTimeField(blank=False, null=False)

    class Meta:
        ordering = ('-id',)
    
    def __str__(self):
        return 'order:{},{},{},{},{},{},{}'.format(self.orderid, self.customer, self.contact,self.deposit, self.price, self.effectdays, self.balance)
    
    def get_effect_days(self):
        date_format = "%m/%d/%Y"
        now = datetime.datetime.now()
        print ("=============================date", self.orderdate)
        print ("=============================comment", self.comment)
        delta = now - self.orderdate
        return delta.days + 1

    def get_balance(self):
        balance = self.deposit - self.price * self.get_effect_days() 
        return balance

    def get_after7days_expire(self):
        if self.balance < self.price * 7 :
            return 1 
        else:
            return 0

    def get_after7days_expire(self):
        if self.balance < self.price * 3 :
            return 1 
        else:
            return 0

    def get_expired(self):
        if self.balance < 0 :
            return 1 
        else:
            return 0

project/templates/accountbak/XadminLogin.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>后台登录-乐乐</title>
	<meta name="renderer" content="webkit|ie-comp|ie-stand">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi" />
    <meta http-equiv="Cache-Control" content="no-siteapp" />

    <!--link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" /-->
    <link rel="stylesheet" href="{% static 'xadmin/css/font.css' %}">
	<link rel="stylesheet" href="{% static 'xadmin/css/xadmin.css' %}">
    <script type="text/javascript" src="{% static 'xadmin/js/jquery-3.2.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'xadmin/js/layui/layui.js' %}" charset="utf-8"></script>
    <script type="text/javascript" src="{% static 'xadmin/js/xadmin.js' %}"></script>

</head>
<body class="login-bg">
    <div class="login layui-anim layui-anim-up">
        <div class="message">Le管理登录Le</div>
        <div id="darkbannerwrap"></div>
        
        <form action="{% url 'account:user_login' %}" method="post" class="layui-form" >{% csrf_token %}
            <input name="username" placeholder="用户名"  type="text" lay-verify="required" class="layui-input">
            <hr class="hr15">
            <input name="password" lay-verify="required" placeholder="密码"  type="password" class="layui-input">
            <hr class="hr15">
            <input value="登录" lay-submit lay-filter="login" style="width:100%;" type="submit">
            <hr class="hr20" >
        </form>
    </div>
</body>
</html>

project/templates/accountbak/login.html
{% extends "account/base.html" %}
{% block content %}
<div class="login-container">
	<div class="position-relative">
		<div id="login-box" class="login-box visible widget-box no-border">
			<div class="widget-body">
				<div class="widget-main">
					<h4 class="header blue lighter bigger">
						<i class="ace-icon fa fa-coffee green"></i>
						Please Enter Your Information
					</h4>

					<div class="space-6"></div>
					<form action="{% url 'account:user_login' %}" method="post" >{% csrf_token %}
						<fieldset>
							<label class="block clearfix">
								<span class="block input-icon input-icon-right">
									<input name="username" type="text" class="form-control" placeholder="用户名" value="{{request.POST.username}}" />
									<i class="ace-icon fa fa-user"></i>
								</span>
							</label>

							<label class="block clearfix">
								<span class="block input-icon input-icon-right">
									<input name="password" type="password" class="form-control" placeholder="密码" value="{{request.POST.password}}" />
									<i class="ace-icon fa fa-lock"></i>
								</span>
							</label>

							<div class="space"></div>

							<div class="clearfix">
								<label class="inline">
									<input type="checkbox" class="ace" />
									<span class="lbl"> Remember Me</span>
								</label>

								<button type="submit" class="width-35 pull-right btn btn-sm btn-primary">
									<i class="ace-icon fa fa-key"></i>
									<span class="bigger-110">Login</span>
								</button>
							</div>

							<div class="space-4"></div>

							<label class="block red center">
                                {% if form.errors|length == 1 %}
                                 Info: Username Or Password is error.
                                {% endif %}
							</label>

						</fieldset>
					</form>
				</div><!-- /.widget-main -->

				<div class="toolbar clearfix">
					<div>
						<a href="{% url 'account:password_reset' %}" data-target="#forgot-box" class="forgot-password-link">
							<i class="ace-icon fa fa-arrow-left"></i>
							I forgot my password
						</a>
					</div>

					<div>
						<a href="#" data-target="#signup-box" class="user-signup-link">
							I want to register
							<i class="ace-icon fa fa-arrow-right"></i>
						</a>
					</div>
				</div>
			</div><!-- /.widget-body -->
		</div><!-- /.login-box -->
                
		<div id="forgot-box" class="forgot-box widget-box no-border">
			<div class="widget-body">
				<div class="widget-main">
					<h4 class="header red lighter bigger">
						<i class="ace-icon fa fa-key"></i>
						Retrieve Password
					</h4>

					<div class="space-6"></div>
					<p>
						Enter your email and to receive instructions
					</p>

					<form action="{% url 'account:password_reset' %}" method="post">{% csrf_token %}
						<fieldset>
							<label class="block clearfix">
								<span class="block input-icon input-icon-right">
									<input id="id_email" name="email" type="email" class="form-control" placeholder="Email" />
									<i class="ace-icon fa fa-envelope"></i>
								</span>
							</label>

							<div class="clearfix">
								<button type="submit" class="width-35 pull-right btn btn-sm btn-danger">
									<i class="ace-icon fa fa-lightbulb-o"></i>
									<span class="bigger-110">Send Me!</span>
								</button>
							</div>
						</fieldset>
					</form>
				</div><!-- /.widget-main -->

				<div class="toolbar center">
					<a href="#" data-target="#login-box" class="back-to-login-link">
						Back to login
						<i class="ace-icon fa fa-arrow-right"></i>
					</a>
				</div>
			</div><!-- /.widget-body -->
		</div><!-- /.forgot-box -->

		<div id="signup-box" class="signup-box widget-box no-border">
			<div class="widget-body">
				<div class="widget-main">
					<h4 class="header green lighter bigger">
						<i class="ace-icon fa fa-users blue"></i>
						New User Registration
					</h4>

					<div class="space-6"></div>
					<p> Enter your details to begin: </p>

					<form action="{% url 'account:user_register' %}" method="post">{% csrf_token %}
						<fieldset>
							<label class="block clearfix">
								<span class="block input-icon input-icon-right">
									<input id="id_email" name="email" type="email" class="form-control" placeholder="Email" />
									<i class="ace-icon fa fa-envelope"></i>
								</span>
							</label>

							<label class="block clearfix">
								<span class="block input-icon input-icon-right">
									<input id="id_username" name="username" type="text" class="form-control" placeholder="Username" />
									<i class="ace-icon fa fa-user"></i>
								</span>
							</label>

							<label class="block clearfix">
								<span class="block input-icon input-icon-right">
									<input id="id_password" name="password" type="password" class="form-control" placeholder="Password" />
									<i class="ace-icon fa fa-lock"></i>
								</span>
							</label>

							<label class="block clearfix">
								<span class="block input-icon input-icon-right">
									<input id="id_password2" name="password2"  type="password" class="form-control" placeholder="Repeat password" />
									<i class="ace-icon fa fa-retweet"></i>
								</span>
							</label>

							<label class="block">
								<input type="checkbox" class="ace" />
								<span class="lbl">
									I accept the
									<a href="#">User Agreement</a>
								</span>
							</label>

							<div class="space-24"></div>

							<div class="clearfix">
								<button type="reset" class="width-30 pull-left btn btn-sm">
									<i class="ace-icon fa fa-refresh"></i>
									<span class="bigger-110">Reset</span>
								</button>

								<button type="submit" class="width-65 pull-right btn btn-sm btn-success">
									<span class="bigger-110">Register</span>

									<i class="ace-icon fa fa-arrow-right icon-on-right"></i>
								</button>
							</div>
						</fieldset>
					</form>
				</div>

				<div class="toolbar center">
					<a href="#" data-target="#login-box" class="back-to-login-link">
						<i class="ace-icon fa fa-arrow-left"></i>
						Back to login
					</a>
				</div>
			</div><!-- /.widget-body -->
		</div><!-- /.signup-box -->
	</div><!-- /.position-relative -->
</div>
{% endblock %}

project/templates/accountbak/password_reset_complete.html
{% extends "account/base.html" %}
{% load i18n %}
{% block content %}
<div class="col-sm-6 col-sm-offset-3">
	<div class="position-relative">
		<div id="forgot-box" class="forgot-box widget-box no-border visible">
			<div class="widget-body">
				<div class="toolbar center">
					<span class="back-to-login-link">
						prompt Info
					</span>
				</div>
			
				<div class="widget-main">
					<h4 class="header red lighter bigger">
						<i class="ace-icon fa fa-lock"></i>
                        {{ title }}
					</h4>

					<div class="space-6"></div>
                    <p>{% trans "Your password has been set.  You may go ahead and log in now." %}</p>
                    <p class="center"><a href="{{ login_url }}">{% trans 'Log in' %}</a></p>
				</div><!-- /.widget-main -->

			</div><!-- /.widget-body -->
		</div><!-- /.forgot-box -->
	</div><!-- /.position-relative -->
</div>
{% endblock %}

project/templates/accountbak/password_reset_email.html
<p>你收到这封邮件是因为你忘记本站密码,需要重置</p>
<p>Please go to the floowing page and choose a new password:</p>
{{protocol}}://{{domain}}{% url 'account:password_reset_confirm' uidb64=uid token=token %}
<p>Your username, in case you've forgotten:{{ user.get_username }}</p>
<p>thanks for using our site!</p>

project/templates/accountbak/user_profile.html
{% extends "frame/base.html" %}
{% load staticfiles %}
{% block content %}
<link rel="stylesheet" href="{% static 'layui/css/layui.css' %}" />

<div id="user-profile-3" class="user-profile row">
	<div class="col-sm-offset-1 col-sm-10">
			<div class="tabbable">
				<ul class="nav nav-tabs padding-16">
					<li {% if tab == '1' %}class="active" {% endif %}>
						<a href="{% url 'account:user_profile' 1 %}">
							<i class="green ace-icon fa fa-pencil-square-o bigger-125"></i>
							Basic Info 
						</a>
					</li>

					<li {% if tab == '2' %}class="active" {% endif %}>
						<a  href="{% url 'account:user_profile' 2 %}">
							<i class="blue ace-icon fa fa-key bigger-125"></i>
							Password 
						</a>
					</li>
				</ul>

				<div class="tab-content profile-edit-tab-content">
                    {% if msg %}
                    <div {% if msg == '1' %}class="alert alert-success"{% elif msg == '2'%}class="alert alert-danger"{% endif %}>
                        <a href="#" class="close" data-dismiss="alert">
                            &times;
                        </a>
                        {% if msg == '1' %}
                        <strong>Success！</strong> Modify Success.
                        {% elif msg == '2' %}
                        <strong>Warning！</strong>Modify Error, Please Check ...
                        {% endif %}
                    </div>
                    {% endif %}

					<div id="edit-basic" {% if tab == '1' %} class="tab-pane in active" {% else %} class="tab-pane" {% endif %}>
                        <div class="row">
                            <div class="col-sm-7">
						        <form class="form-horizontal" action="{% url 'account:save_userinfo' %}" method="post">{% csrf_token %}
						        	<h4 class="header blue bolder smaller">General</h4>

						        	<div class="form-group">
						        		<label class="col-sm-3 control-label no-padding-right" >Username :</label>

						        		<div class="col-sm-9">
						        		<label class="control-label padding-left">{{ user.username }}</label>
						        		</div>
						        	</div>

						        	<div class="space-4"></div>

						        	<div class="form-group">
						        		<label class="col-sm-3 control-label no-padding-right" for="id_name">Name :</label>

						        		<div class="col-sm-9">
						        			<input class="col-xs-12 col-sm-10 input-large" type="text" id="id_name" name="name" placeholder="Name" value="{{ userinfo.name}}" />
						        		</div>
						        	</div>

						        	<div class="space-4"></div>

						        	<div class="form-group">
						        		<label class="col-sm-3 control-label no-padding-right">Gender :</label>

						        		<div class="col-sm-9">
						        		    <label class="control-label">
						        				<input name="gender" type="radio" class="ace" {% if userinfo.gender is True  or userinfo.gender == "1" %} checked="checked" {% endif %} value="1" />
						        				<span class="lbl middle"> Male</span>
                                            </label>
						        			&nbsp; &nbsp; &nbsp;
						        		    <label class="control-label">
						        				<input name="gender" type="radio" class="ace"{% if userinfo.gender is False or userinfo.gender == "0" %} checked="checked" {% endif %}  value="0"/>
						        				<span class="lbl middle"> Female</span>
                                            </label>
						        		</div>
						        	</div>

						        	<div class="space-4"></div>

						        	<div class="form-group">
						        		<label class="col-sm-3 control-label no-padding-right" for="id_birth">Birth Date :</label>

						        		<div class="col-sm-9">
						        			<div class="input-large">
						        				<div class="input-group">
						        					<input class="input-large" id="id_birth" name="birth" type="text" data-date-format="yyyy-mm-dd" placeholder="yyyy-mm-dd" value="{{ userinfo.birth | date:"Y-m-d" }}" readonly=""/>
						        					<span class="input-group-addon">
						        						<i class="ace-icon fa fa-calendar"></i>
						        					</span>
						        				</div>
						        			</div>
						        		</div>
						        	</div>

						        	<div class="space-4"></div>

						        	<div class="form-group">
						        		<label class="col-sm-3 control-label no-padding-right" for="id_email">Email :</label>

						        		<div class="col-sm-9">
                                            <div class="row">
						        		        <div class="col-sm-5">
						        		    	    <span class="input-icon input-icon-right">
						        		    	    	<i class="ace-icon fa fa-envelope"></i>
						        		    	    	<input class="col-xs-12 col-sm-10 input-large"  type="email" id="id_email" name="email" value="{{ user.email }}" />
						        		    	    </span>
						        		        </div>

						        		        <div class="col-sm-6">
								                    <label class="control-label padding-left red">{{ user_form.email.errors }}</label>
						        		        </div>
						        		    </div>
						        		</div>
						        	</div>

						        	<div class="space-4"></div>

						        	<div class="form-group">
						        		<label class="col-sm-3 control-label no-padding-right" for="id_website">Website :</label>

						        		<div class="col-sm-9">
						        		    <div class="row">
						        		        <div class="col-sm-5">
						        			        <span class="input-icon input-icon-right">
						        			        	<input class="col-xs-12 col-sm-10 input-large"  type="url" id="id_website" name="website" placeholder="http://" value="{{ userinfo.website}}" />
						        			        	<i class="ace-icon fa fa-globe"></i>
						        			        </span>
						        		        </div>

						        		        <div class="col-sm-6">
								                    <label class="control-label padding-left red">{{ userinfo_form.website.errors }}</label>
						        		        </div>
						        		    </div>
						        		</div>
						        	</div>

						        	<div class="space-4"></div>

						        	<div class="form-group">
						        		<label class="col-sm-3 control-label no-padding-right" for="id_phone">Phone :</label>

						        		<div class="col-sm-9">
						        			<span class="input-icon input-icon-right">
						        				<input class="col-xs-12 col-sm-10 input-large input-mask-phone" type="text" id="id_phone" name="phone" value="{{ userinfo.phone }}"/>
						        				<i class="ace-icon fa fa-phone fa-flip-horizontal"></i>
						        			</span>
						        		</div>
						        	</div>

						        	<div class="form-group">
						        		<label class="col-sm-3 control-label no-padding-right" for="id_comment">Comment :</label>

						        		<div class="col-sm-9">
						        			<textarea class="input-large" id="id_comment" name="comment">{{ userinfo.comment }}</textarea>
						        		</div>
						        	</div>

						        	<div class="space-4"></div>

						        	<div class="from-group clearfix">
						        		<div class="col-md-offset-3 col-md-9">
						        			<button class="btn btn-info" type="submit">
						        				<i class="ace-icon fa fa-check bigger-110"></i>
						        				Save
						        			</button>

						        			&nbsp; &nbsp;
						        			<button class="btn" type="reset">
						        				<i class="ace-icon fa fa-undo bigger-110"></i>
						        				Reset
						        			</button>
						        		</div>
						        	</div>
						        </form>
                            </div>
                            <div class="col-sm-5">
                                <style>
                                   .sgl_headImg{
                                        margin:auto;
                                        width:200px;
                                        height:200px;
                                        cursor:pointer;
                                    } 
                                </style>
						        <h4 class="header blue bolder smaller">Head portrait</h4>
                                <div class="row">
                                    {% if userinfo.photo %}
                                    <img class="img-circle img-responsive sgl_headImg" name="user_face" title="click & modify" src="{{ userinfo.photo | striptags }}" onclick="upload_image_layer()">
                                    {% else %}
                                    <img class="img-circle img-responsive sgl_headImg" name="user_face" title="click & modify" src="{% static 'images/wolf.jpg' %}" onclick="upload_image_layer()">
                                    {% endif %}
                                </div>
                            </div>
                        </div>
					</div>


					<div id="edit-password" {% if tab == '2' %} class="tab-pane in active" {% else %} class="tab-pane" {% endif %}>
						<form class="form-horizontal" method="post" action="{% url 'account:password_change' %}">{% csrf_token %}
							<div class="space-10"></div>

							<div class="form-group">
								<label class="col-sm-3 control-label no-padding-right" for="id_old_password">Old Password</label>

								<div class="col-sm-9">
									<input class="col-xs-4" name="old_password" type="password" id="id_old_password" />
								    <label class="control-label no-padding-left red">{{ form.old_password.errors }}</label>
								</div>
							</div>

							<div class="space-4"></div>
							<div class="form-group">
								<label class="col-sm-3 control-label no-padding-right" for="id_new_password1">New Password</label>

								<div class="col-sm-9">
									<input class="col-xs-4" name="new_password1" type="password" id="id_new_password1" />
								    <label class="control-label no-padding-left red">{{ form.new_password1.errors }}</label>
								</div>
							</div>

							<div class="space-4"></div>

							<div class="form-group">
								<label class="col-sm-3 control-label no-padding-right" for="id_new_password2">Confirm Password</label>

								<div class="col-sm-9">
									<input class="col-xs-4" name="new_password2" type="password" id="id_new_password2" />
								    <label class="control-label no-padding-left red">{{ form.new_password2.errors }}</label>
								</div>
							</div>

							<div class="space-4"></div>

							<div class="form-group">
								<label class="col-sm-3 control-label no-padding-right"></label>
								<div class="col-md-offset-3 col-md-9">
									<button class="btn btn-info" type="submit">
										<i class="ace-icon fa fa-check bigger-110"></i>
										Save
									</button>

									&nbsp; &nbsp;
									<button class="btn" type="reset">
										<i class="ace-icon fa fa-undo bigger-110"></i>
										Reset
									</button>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
	</div><!-- /.span -->
</div><!-- /.user-profile -->
{% endblock %}

{% block jsscript%}
<script type="text/javascript"  src="{% static 'assets/js/jquery.gritter.min.js' %}"></script>
<script type="text/javascript"  src="{% static 'assets/js/bootstrap-datepicker.min.js' %}"></script>
<script type="text/javascript"  src="{% static 'assets/js/jquery.hotkeys.index.min.js' %}"></script>
<script type="text/javascript"  src="{% static 'assets/js/jquery.maskedinput.min.js' %}"></script>
<script type="text/javascript" src="{% static 'layui/layui.js' %}"></script>
<!-- inline scripts related to this page -->
<script type="text/javascript">
	jQuery(function($) {
		$('.input-mask-phone').mask('999-9999-9999');

        layui.use("laydate", function(){
            var laydate= layui.laydate;
            laydate.render({
                elem: '#id_birth',//指定元素
                showBottom: false,
                trigger:'click'
            });
        });
	});

	function upload_image_layer(){
        layui.use("layer", function(){
            var layer = layui.layer;
		    layer.open({
		    	title:"Upload the picture",	
		    	area: ['650px','520px'],
		    	type: 2,
		    	content: "{% url 'account:my_headimage' %}",
		    });
        });
	}
</script>
{% endblock %}