project/customer/urls.py
from django.contrib import admin
from django.urls import path,re_path
from django.conf.urls import url,include
from django.views.generic import TemplateView
from . import views as customer_views

from django.conf import settings

app_name='customer'
urlpatterns = [
    path('list', customer_views.CustomerListPageView.as_view(), name='show_customerList'),
    path('add', customer_views.CustomerAddPageView.as_view(), name='show_customerAdd'),
    path('<int:pk>/delete', customer_views.CustomerDelPageView.as_view(), name='show_customerDel'),
    path('<int:pk>/detail', customer_views.CustomerDetailPageView.as_view(), name='show_customerDetail'),
    path('<int:pk>/update', customer_views.CustomerUpdatePageView.as_view(), name='show_customerUpdate'),

    ##修改记录时有两种方式
    ##一是先用DetailView类获取要修改的对象将对象的数据回显到修改表单中,再使用UpdateView类去更新对象
    ##二是直接使用UpdateView类对象,在XXX_UpdateView类中添加一个获取对象的函数即可(get_context_data)
]

project/main/urls.py
from django.contrib import admin
from django.urls import path,re_path
from django.conf.urls import url,include
from django.views.generic import TemplateView

from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

from account import views as auth_views
from common import views as comm_views

urlpatterns = [
    #登录页
    #直接访问IP:port 后边不用加路径, 即http://192.168.5.105:8000就会跳转到login.html
    #方法一,这样不会在html模板中使用{{form.password}}
	#url('', TemplateView.as_view(template_name="account/login.html"), name='show_loginPage'),
    #方法二,这样可以在html模板中使用{{form.password}}
	path('', auth_views.LoginView.as_view(template_name='account/login.html'), name="show_loginPage"),

    #登录之后跳转到该页,该页即首页
    path('index/', comm_views.IndexPageView.as_view(), name='show_index'),
    path('homepage/', comm_views.HomePageView.as_view(), name='show_homePage'),

    #账户相关
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),

    #客户相关
    path('index/customer/', include('customer.urls', namespace='customer')),

    #订单相关
    path('index/order/', include('order.urls', namespace='order')),

    re_path(r'media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/customer/models.py
from django.db import models
from django.conf import settings

# Create your models here.

class CustomerModel(models.Model):
    name = models.CharField(max_length=100, blank=False, null=False)
    contact = models.CharField(max_length=24, blank=False, null=False)
    phone = models.CharField(max_length=11, blank=False, null=False)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-id',)
    
    def __str__(self):
        return 'customer:{},{},{}'.format(self.name, self.contact, self.phone, self.created)

project/customer/forms.py
from django import forms
from .models import CustomerModel

class CustomerAddForm(forms.ModelForm):
    class Meta:
        model = CustomerModel 
        fields = ("name","contact","phone",)

project/customer/views.py
from django.shortcuts import render, redirect
from braces.views import LoginRequiredMixin
from django.views.generic import CreateView, ListView, DeleteView, UpdateView, DetailView
from django.views.generic.base import TemplateView
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.http import HttpResponse, JsonResponse
from django.core.exceptions import ObjectDoesNotExist
import json

from .models import CustomerModel as Customer
from .forms import CustomerAddForm 

# Create your views here.

##BEGIN: Add by SRJ-SGL 
#客户列表
class CustomerListPageView(LoginRequiredMixin, ListView):
    ## login_url = "/account/login/"  和下边一行的功能是一样的,一个是硬编码,一个是灵活实现
    login_url = reverse_lazy('user_login') 
    template_name = "customer/customer-list.html"

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request, *args, **kwargs):
        ## 过滤条件参数
        ## 判断是搜索的数据还是直接显示的数据
        q = {}
        page = request.POST.get('page')
        rows = request.POST.get('limit')

        filter_name = request.POST.get('filter_name')         
        filter_contact = request.POST.get('filter_contact')         
        filter_phone = request.POST.get('filter_phone')         

        if filter_name:
            ##'name' + __icontains 是name忽略大小写的意思
            q['name__icontains'] = filter_name
        if filter_contact:
            q['contact__icontains'] = filter_contact
        if filter_phone:
            q['phone__icontains'] = filter_phone

        customers = Customer.objects.filter(**q)

        start = (int(page) - 1) * int(rows)
        end = (int(page) - 1) * int(rows) + int(rows)

        total = customers.count()
        customers = customers[start:end]

        dict = []
        resultdict = {}

        for tmp in customers:
            dic = {}
            dic['id'] = tmp.id
            dic['name'] = tmp.name
            dic['contact'] = tmp.contact
            dic['phone'] = tmp.phone
            dic['created'] = tmp.created.strftime("%Y-%m-%d %H:%M:%S")
            dict.append(dic)

        resultdict['code'] = 0
        resultdict['msg'] = ""
        resultdict['count'] = total 
        resultdict['data'] = dict

        return JsonResponse(resultdict, safe=False) 

class CustomerAddPageView(LoginRequiredMixin, CreateView):
    login_url = "/account/login/"
    template_name = "customer/customer-add.html"
    fields = ['name', 'contact', 'phone']

    ##Note1 当继承的是TemplateView时使用这个
    ##def get(self, request):
    ##    return render(request, "customer/customer-add.html")
    
    ##Note2 当继承的是CreateView时使用这个,功能与Note1是一样的,只是两种不同的实现方式
    queryset = Customer.objects.all()

    def post(self, request, *args, **kwargs):
        formObj = CustomerAddForm(request.POST)
        resultdict = {}

        if formObj.is_valid():
            form_cd = formObj.cleaned_data 
            new_customer = formObj.save(commit=False)
            new_customer.save(form_cd)

            resultdict['code'] = 0
            resultdict['msg'] = ""
            return JsonResponse(resultdict, safe=False) 
            ##return redirect("customer:show_customerList")

        return self.render_to_response({"form":formObj})

class CustomerDelPageView(LoginRequiredMixin, DeleteView):
    login_url = "/account/login/"
    success_url = reverse_lazy('customer:show_customerList')

    model = Customer

    def delete(self, request, *args, **kwargs):
        ##for k, v in kwargs.items():
        ##    print ('%s，%s；' , (k, v))
        super(CustomerDelPageView, self).delete(request, *args, **kwargs)
        return JsonResponse({'code':0, 'msg':''}) 

class CustomerDetailPageView(LoginRequiredMixin, DetailView):
    template_name = "customer/customer-update.html"
    context_object_name = "customer"

    model = Customer

    ##如果不要下边的这个函数,是不会把信息返回到表单的
    ##def get_object(self, queryset=None):
    ##    obj = super(CustomerDetailPageView, self).get_object()
    ##    return obj

    ##下边注释的两个函数其实放开效果是一样的,只不过是记录一下怎么取url中的参数的方法
    ##def get_object(self,queryset=None):
    ##    obj_id = int(self.kwargs.get(self.pk_url_kwarg, None))
    ##    obj = self.model.objects.get(id = obj_id)
    ##    return obj 
    
    def get_context_data(self, **kwargs):
        context = super(CustomerDetailPageView, self).get_context_data(**kwargs)
        return context

class CustomerUpdatePageView(LoginRequiredMixin, UpdateView):
    login_url = "/account/login/"
    success_url = reverse_lazy('customer:show_customerList')

    template_name = "customer/customer-update.html"
    template_name_suffix = '_update_form'
    fields = ['name', 'contact', 'phone']
    context_object_name = "customer"

    model = Customer

    ##以下的方式也可以用,相当于自己实现更新这个功能
    ##form_class = CustomerAddForm 

    ##def get_context_data(self, **kwargs):
    ##    context = super(CustomerUpdatePageView,self).get_context_data(**kwargs)
    ##    return context

    ##def post(self, request, *args, **kwargs):
    ##    formObj = CustomerAddForm(request.POST)
    ##    resultdict = {}

    ##    if formObj.is_valid():
    ##        form_cd = formObj.cleaned_data 

    ##        original = super(CustomerUpdatePageView, self).get_object()
    ##        ##original.customer = form_cd['name']
    ##        ##original.contact= form_cd['contact']
    ##        ##original.phone= form_cd['phone']
    ##        original.save(form_cd)

    ##        resultdict['code'] = 0
    ##        resultdict['msg'] = ""
    ##        return JsonResponse(resultdict, safe=False) 

    ##    resultdict['code'] = 1
    ##    resultdict['msg'] = "update failed."
    ##    return JsonResponse(resultdict, safe=False) 

##END: Add by SRJ-SGL 

project/templates/customer/customer-add.html
{% extends "frame/tabpages.html" %}
{% block content %}
<body>
    <div class="layui-fluid">
        <div class="layui-row">
            <form class="layui-form" id="id_addCustomerForm">{% csrf_token %}
                <div class="layui-form-item">
                    <label for="id_name" class="layui-form-label">
                        <span class="x-red">*</span>客户名称</label>
                    <div class="layui-input-inline">
                        <input type="text" id="id_name" name="name" required="" lay-verify="required" autocomplete="off" class="layui-input" value="aa">
                    </div>
                </div>
                <div class="layui-form-item">
                    <label for="id_contact" class="layui-form-label">
                        <span class="x-red">*</span>联系人</label>
                    <div class="layui-input-inline">
                        <input type="text" id="id_contact" name="contact" required="" lay-verify="required" autocomplete="off" class="layui-input" value="bb"></div>
                </div>
                <div class="layui-form-item">
                    <label for="id_phone" class="layui-form-label">
                        <span class="x-red">*</span>联系方式</label>
                    <div class="layui-input-inline">
                        <input type="text" id="id_phone" name="phone" required="" lay-verify="phone" autocomplete="off" class="layui-input" value="12345678901">
                    </div>
                </div>
                <div class="layui-form-item">
                    <label class="layui-form-label"></label>
                    <button class="layui-btn" lay-filter="add" lay-submit="">增加</button>
                    <button class="layui-btn" lay-filter="continue" lay-submit="">增加后继续</button>
                </div>
            </form>
        </div>
    </div>
</body>
{% endblock %}

{% block jsscript %}
<script>
layui.use(['form', 'layer','jquery'],
    function() {
        $ = layui.jquery;
        var form = layui.form,
        layer = layui.layer;

        //监听提交
        form.on('submit(add)',
        function(data) {
            $.ajax({
                type:'post',
                url:"{% url 'customer:show_customerAdd' %}",
                data:data.field,
                //data:{name:name,contact:contact, phone:phone,csrfmiddlewaretoken: '{{ csrf_token }}'}, //等价于data: data.field;
                success:function(res){
                    if (res.code == 0)
                    {
                        layer.alert("添加成功", {icon: 6},function() {
                            xadmin.close();//关闭当前frame
                            xadmin.father_reload();// 可以对父窗口进行刷新 
                        });
                    }
                },
                error:function(res)
                {
                    layer.msg("添加失败.");
                }
            });
                       
            return false;
        });

        form.on('submit(continue)',
        function(data) {
            $.ajax({
                type:'post',
                url:"{% url 'customer:show_customerAdd' %}",
                data:data.field,
                success:function(res){
                    if (res.code == 0)
                    {
                        layer.msg("添加成功,继续添加下一个.");
                        $("#id_addCustomerForm")[0].reset();
                    }
                },
                error:function(res)
                {
                    layer.msg("添加失败.");
                }
            });
                       
            return false;
        });
    });
</script>
{% endblock %}

project/templates/customer/customer-list.html
{% extends "frame/tabpages.html" %}
{% block content %}
<body>
    <div class="layui-fluid">
        <div class="layui-row layui-col-space15">
            <div class="layui-col-md12">
                <div class="layui-card">
                    <div class="layui-card-body ">
                        <form class="layui-form layui-col-space5" id="id_searchCustomerForm">{% csrf_token %}
                            <div class="layui-inline layui-show-xs-block">
                                <input class="layui-input" type="text" name="filter_name"  placeholder="客户名称" id="id_name">
                            </div>
                            <div class="layui-inline layui-show-xs-block">
                                <input class="layui-input" type="text" name="filter_contact" placeholder="联系人" id="id_contact">
                            </div>
                            <div class="layui-inline layui-show-xs-block">
                                <input class="layui-input" type="text" name="filter_phone" placeholder="联系电话" id="id_phone">
                            </div>
                            <div class="layui-inline layui-show-xs-block xxxListButton">
                                <!--不能用button,如果使用button的话,会发送两次请求.
                                    button 的type button默认为type的值为submit,submit会默认提交一次,
                                    再加上js里的提交就会出现重复提交的问题,把type的值改为button就可以解决问题了-->
                                <!--button class="layui-btn"  data-type="reload" lay-submit="" lay-filter="search"><i class="layui-icon">&#xe615;</i>查询</button-->
                                <a class="layui-btn"  id="searchBtn" data-type="reload" lay-submit=""><i class="layui-icon">&#xe615;</i>查询</a>
                                <a class="layui-btn"  id="resetBtn" data-type="reset" lay-submit=""><i class="layui-icon">&#xe666;</i>重置</a>
                            </div>
                        </form>
                    </div>
                    <div class="layui-card-body layui-table-body layui-table-main">
                        <table id="id_customerlist" class="layui-table layui-form"  lay-filter="f_customerlist">
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div> 
{% include "frame/searchBindMode.html" %}
</body>
{% endblock %}

{% block jsscript %}
<script type="text/html" id="toolbarCustomerList">
    <div class="layui-btn-group xxxListButton">
        <a class="layui-btn layui-btn-danger" data-type="delAllChecked"><i class="layui-icon"></i>批量删除</a> 
        <a class="layui-btn" onclick="xadmin.open('添加用户','add',600,400)"><i class="layui-icon"></i>添加</a>
        <a class="layui-btn layui-btn-small" onclick="location.reload()" id= "id_refresh" title="刷新">
            <i class="layui-icon layui-icon-refresh"></i>
        </a>
    </div>
</script>

<script type="text/html" id="toolbarOper">
    <a class="layui-btn layui-btn-xs" lay-event="edit">编辑</a>
    <a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="del">删除</a>
</script>

<script>
layui.use(['jquery','table'], function(){
    var table = layui.table;
    var $ = layui.$

    table.render({
        elem: '#id_customerlist', 
        method: 'post',
        url: "{% url 'customer:show_customerList' %}", //数据接口
        height: 'full-180',
        page: true, //开启分页
        limit: 10,
        toolbar: '#toolbarCustomerList',
        defaultToolbar: ['filter', 'exports', 'print', { //自定义头部工具栏右侧图标。如无需自定义，去除该参数即可
            title: '提示',
            layEvent: 'LAYTABLE_TIPS',
            icon: 'layui-icon-tips',
            }],
        cols: [[ //表头
            {type: 'checkbox', width:'10%',},
            {type: 'numbers', title: '序号',         width:'10%', align:'center'},
            {field: 'name', title: '客户名称',   width:'20%', align:'center', sort: true},
            {field: 'contact',  title: '联系人',     width:'15%', align:'center', sort: true},
            {field: 'phone',    title: '联系电话',   width:'15%', align:'center', sort: true},
            {field: 'created',  title: '添加时间',   width:'15%', align:'center', sort: true},
            {title: '操作', toolbar: '#toolbarOper', width:'15%', align:'center'}
        ]]
    });  
    
    table.on('tool(f_customerlist)', function(obj){
        var data = obj.data;
        if(obj.event === 'del'){
            layer.confirm('确定要删除?', function(index){
                $.ajax({
                    type:'post',
                    url:"{% url 'customer:show_customerDel' 0 %}".replace('0', data.id),
                    data:{},
                    success:function(res){
                        if (res.code == 0)
                        {
                            layer.msg("删除成功!");
                            obj.del();
                            layer.close(index);
                        }

                    },
                    error:function(res)
                    {
                        layer.msg("删除失败!");
                    }
                });
            });
        } else if(obj.event === 'edit'){
            uri = obj.data.id + '/update'; 
            xadmin.open('编辑用户',uri,600,400);
        }

    });

    active = {
        delAllChecked: function(){ //获取选中数据
            var checkStatus = table.checkStatus('id_customerlist');
            data = checkStatus.data;
            data.forEach((item, index, array)=>{
                $.ajax({
                    type:'post',
                    url:"{% url 'customer:show_customerDel' 0 %}".replace('0', item.id),
                    data:{},
                    success:function(res){
                        if (res.code == 0)
                        {
                            layer.msg("删除成功!");
                            location.reload();
                        }
                    },
                    error:function(res)
                    {
                        layer.msg("删除失败!");
                    }
                });
            })
        },
        reload: function(){
            table.reload('id_customerlist', {
                page: {
                    curr: 1 //重新从第 1 页开始
                },
                where: {
                   filter_name: $("input[name=filter_name]").val(),
                   filter_contact: $("input[name=filter_contact]").val(),
                   filter_phone: $("input[name=filter_phone]").val()
                }
            });
        },
        reset: function(){
            $("#id_searchCustomerForm")[0].reset();
            $("#id_refresh").click();
        }
    };

    $('.xxxListButton .layui-btn').on('click', function(){
        var type = $(this).data('type');
        active[type] ? active[type].call(this) : '';
    });
});

</script>
{% endblock %}

project/templates/customer/customer-update.html
{% extends "frame/tabpages.html" %}
{% block content %}
<body>
    <div class="layui-fluid">
        <div class="layui-row">
            <form class="layui-form">{% csrf_token %}
                <div class="layui-form-item">
                    <label for="id_name" class="layui-form-label">
                        <span class="x-red">*</span>客户名称</label>
                    <div class="layui-input-inline">
                        <input type="text" id="id_name" name="name" required="" lay-verify="required" autocomplete="off" class="layui-input" value="{{customer.name}}">
                    </div>
                </div>
                <div class="layui-form-item">
                    <label for="id_contact" class="layui-form-label">
                        <span class="x-red">*</span>联系人</label>
                    <div class="layui-input-inline">
                        <input type="text" id="id_contact" name="contact" required="" lay-verify="required" autocomplete="off" class="layui-input" value="{{customer.contact}}"></div>
                </div>
                <div class="layui-form-item">
                    <label for="id_phone" class="layui-form-label">
                        <span class="x-red">*</span>联系方式</label>
                    <div class="layui-input-inline">
                        <input type="text" id="id_phone" name="phone" required="" lay-verify="phone" autocomplete="off" class="layui-input" value="{{customer.phone}}">
                    </div>
                </div>
                <div class="layui-form-item">
                    <label class="layui-form-label"></label>
                    <button class="layui-btn" lay-filter="update" lay-submit="">修改</button>
                </div>
            </form>
        </div>
    </div>
</body>
{% endblock %}

{% block jsscript %}
<script>
layui.use(['form', 'layer','jquery'],
    function() {
        $ = layui.jquery;
        var form = layui.form,
        layer = layui.layer;

        //监听提交
        form.on('submit(update)',
        function(data) {
            //发异步，把数据提交给php
            $.ajax({
                type:'post',
                url:"{% url 'customer:show_customerUpdate' 00 %}".replace('0', {{customer.id}}),
                data:data.field,
                success:function(res){
                        layer.msg("更新成功!");
                        xadmin.close();//关闭当前frame
                        xadmin.father_reload();// 可以对父窗口进行刷新 
                },
                error:function(res)
                {
                    layer.msg("更新失败!");
                }
            });
            return false;
        });
    }
);
</script>
{% endblock %}